# Generated by Django 3.2.8 on 2021-10-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecondModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cifra', models.IntegerField(verbose_name='Поля с цифрой')),
            ],
        ),
        migrations.CreateModel(
            name='FirstModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Первое имя')),
                ('second', models.ManyToManyField(to='first_app.SecondModel')),
            ],
        ),
    ]
