# Generated by Django 3.2.8 on 2021-10-26 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstmodel',
            name='new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='new', to='first_app.secondmodel'),
            preserve_default=False,
        ),
    ]
