# Generated by Django 3.2.8 on 2021-10-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20211026_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstmodel',
            name='new',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new', to='first_app.secondmodel'),
        ),
    ]
