# Generated by Django 3.2.8 on 2021-10-26 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_alter_firstmodel_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstmodel',
            name='new',
        ),
    ]
