# Generated by Django 3.2.8 on 2021-10-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_remove_firstmodel_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstmodel',
            name='new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new', to='first_app.secondmodel'),
        ),
    ]
